"""Full-curve check after site-consistent initialization; decoupled sensitivity grid.

The grid is a single-curve diagnostic calibration, not a measured noise spectrum
or a validation of all four Fig. 6 protocols. Paper references are never changed.
"""
from pathlib import Path
import argparse
import json
import hashlib
import zipfile

import numpy as np
import yaml

from continuous_transfer.cli import ROOT, run_case, write_json

OUT = ROOT / "outputs/continuous_level2c_345/run_20260915_manual600_initialization"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase", choices=["scan", "validate"], default="scan")
    parser.add_argument("--temperature", type=float)
    parser.add_argument("--heating-reference", type=float)
    args = parser.parse_args()
    import numba
    numba.set_num_threads(12)
    OUT.mkdir(exist_ok=True, parents=True)
    settings = yaml.safe_load((ROOT / "configs/continuous_level2c_345.yaml").read_text(encoding="utf-8"))
    settings["initial_sampling"] = "site_bound_harmonic"
    settings["max_one_way_transfers"] = 60

    def case(stage, temperature, tref, shots, seed, dt):
        config = settings | {"parametric_reference_temperature_uK": tref}
        case_id = f"{stage}_T{temperature:g}_matched_manual_600us_N{shots}_dt{dt:g}_initSite_Tref{tref:g}"
        file = OUT / (case_id + ".json")
        if file.exists():
            result = json.loads(file.read_text(encoding="utf-8"))
            # Do not silently mix results generated by different source revisions.
            for name, checksum in result["sources"].items():
                assert hashlib.sha256((ROOT / name).read_bytes()).hexdigest() == checksum, name
            return result
        return run_case(config, stage=stage, temperature=temperature, key="manual_600us", arm="matched",
                        shots=shots, seed=seed, dt_us=dt, out=OUT)

    if args.phase == "scan":
        plan = {"purpose": "Diagnose whether independent initial temperature and mean heating can describe manual 600 us",
                "scope": "single-curve sensitivity/calibration only; no experimental input calibration",
                "initial_sampling": "site_bound_harmonic", "one_way_transfers": 60,
                "initial_temperatures_uK": [5, 10, 15, 20, 25],
                "heating_reference_temperatures_uK": [15, 25, 40, 60, 80, 100],
                "scan_shots": 1024, "scan_seed": 24015, "scan_dt_us": .05,
                "fixed_parameter_check": {"temperature_uK": 25, "Tref_uK": 25, "shots": 4096, "seed": 23003, "dt_us": .0125},
                "validation": {"shots": 4096, "seed": 24016, "dt_us": .0125},
                "ranking": "RMSE against unchanged PDF fit path over n=5..60; also require max deviation, markers and early/late behavior to be disclosed",
                "caution": "Temperature and Tref are independent assumed parameters, not measured experimental values."}
        write_json(OUT / "study_plan.json", plan)
        # Freeze source files before the first simulation.
        sources = sorted((ROOT / "src/continuous_transfer").glob("*.py"))
        sources += [Path(__file__).resolve(), ROOT / "configs/continuous_level2c_345.yaml",
                    ROOT / settings["level2c_config"], ROOT / settings["ml_waveform"],
                    ROOT / "reference/fig6d_vector_v2/fig6d_vectors.json"]
        with zipfile.ZipFile(OUT / "study_sources.zip", "w", zipfile.ZIP_DEFLATED) as archive:
            for p in sources:
                archive.write(p, str(p.relative_to(ROOT)))
        fixed = case("initfix", 25, 25, 4096, 23003, .0125)
        rows = []
        for temperature in plan["initial_temperatures_uK"]:
            for tref in plan["heating_reference_temperatures_uK"]:
                result = case("decoupled_scan", temperature, tref, 1024, 24015, .05)
                cp = result["comparison_raw"]
                rows.append({"case_id": result["case_id"], "temperature_uK": temperature, "Tref_uK": tref,
                             "power_uK_per_s": result["heating_power_uK_per_s"]["total"],
                             "S2": result["survival"][2], "S10": result["survival"][10],
                             "S60": result["survival"][60], "rmse": cp["rmse"],
                             "max_deviation": cp["max_abs_deviation"], "passes": cp["matches_reference"],
                             "initial_unbound_actual_site": result["initial_unbound_actual_site"]})
                write_json(OUT / "scan_summary.json", {"rows": rows, "best_so_far": min(rows, key=lambda r: r["rmse"])})
        print("SCAN_RANKING", json.dumps(sorted(rows, key=lambda r: r["rmse"])[:8]), flush=True)
    else:
        if args.temperature is None or args.heating_reference is None:
            parser.error("validate requires temperature and heating-reference")
        result = case("decoupled_validation", args.temperature, args.heating_reference, 4096, 24016, .0125)
        print("VALIDATION", result["case_id"], json.dumps(result["comparison_raw"]), flush=True)


if __name__ == "__main__":
    main()
